# Generated by Django 3.1.7 on 2022-02-08 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('activated', 'active'), ('inactivated', 'inactive'), ('expired', 'expired')], max_length=120)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('number', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cc_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='app.card')),
            ],
        ),
    ]
